configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-wispy-wildflower-abhl4cud-pooler.eu-west-2.aws.neon.tech/ai-boot?user=ai-boot_owner&password=npg_o4qM1hXPwDHV
